#!/bin/bash
save_path = "/content/drive/MyDrive/Chrom2023/Sofia_Examples/$1/movie.mp4"
compressed_path = "/content/drive/MyDrive/Chrom2023/Sofia_Examples/$1/result_compressed.mp4"
os.system(f"ffmpeg -i {save_path} -vcodec libx264 {compressed_path}")
mp4 = open(compressed_path,'rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
HTML("""
<video width=400 controls>
      <source src="%s" type="video/mp4">
</video>
""" % data_url)